import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Engineering track sidebar.
 *
 * Generated from the engineering/ directory structure, the same way the
 * software curriculum sidebar is generated from docs/.
 */
const sidebars: SidebarsConfig = {
  mechanicalSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
