import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Blocks Foundations',
      collapsed: true,
      items: [
        {type: 'link', label: 'Blocks Overview', href: '/blocks'},
        {type: 'link', label: 'Unit 0: How Programs Run', href: '/blocks/blocks-unit-00'},
        {type: 'link', label: 'Unit 1: Values and Variables', href: '/blocks/blocks-unit-01'},
        {type: 'link', label: 'Unit 2: Decisions and Logic', href: '/blocks/blocks-unit-02'},
        {type: 'link', label: 'Unit 3: Loops and Repeated Work', href: '/blocks/blocks-unit-03'},
        {type: 'link', label: 'Unit 4: Functions and Lists', href: '/blocks/blocks-unit-04'},
        {type: 'link', label: 'Unit 5: Plan, Test, and Move to Text Code', href: '/blocks/blocks-unit-05'},
        {type: 'link', label: 'FLL Challenge Extension', href: '/blocks/fll'},
      ],
    },
    {type: 'autogenerated', dirName: '.'},
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
