export type Tier = 'Beginner' | 'Intermediate' | 'Advanced';

export interface CurriculumUnit {
  id: string;
  label: string;
  title: string;
  desc: string;
  tier: Tier;
  slug: string;
  overviewPath: string;
  startPath: string;
  nextPath: string;
  nextLabel: string;
  lessonCount: number;
  overview: string;
  outcomes: string[];
}

export interface CurriculumLesson {
  id: string;
  label: string;
  title: string;
  path: string;
  unitSlug: string;
  unitLabel: string;
  unitTitle: string;
}

export const CURRICULUM_UNITS: CurriculumUnit[] = [
  {
    id: 'UNIT_00',
    label: 'Unit 0',
    title: 'Objects, Classes, and Java',
    desc: 'Learn the Java keywords, classes, objects, references, composition, and shared members you need before using the FTC SDK.',
    tier: 'Beginner',
    slug: 'unit-00',
    overviewPath: '/docs/unit-00',
    startPath: '/docs/unit-00/classes-and-objects',
    nextPath: '/docs/unit-01',
    nextLabel: 'Unit 1: Environment Setup',
    lessonCount: 5,
    overview:
      'A house blueprint can produce separate houses with the same design. Java classes define objects in the same way, while each object keeps its own identity and state.',
    outcomes: [
      'Read foundational Java keywords and distinguish them from types and programmer-chosen names.',
      'Connect classes, objects, fields, constructors, and methods to concrete robot code.',
      'Trace object identity, shared references, null references, and calls across several objects.',
      'Distinguish instance state from static members and static final constants.',
      'Recognize nested classes and use separate top-level files in the Telemark simulator.',
    ],
  },
  {
    id: 'UNIT_01',
    label: 'Unit 1',
    title: 'Environment Setup',
    desc: 'Start in the built-in simulator. Use Android Studio later if your team needs to deploy code to a physical robot.',
    tier: 'Beginner',
    slug: 'unit-01',
    overviewPath: '/docs/unit-01',
    startPath: '/docs/unit-01/prerequisites',
    nextPath: '/docs/unit-02',
    nextLabel: 'Unit 2: OpMode Structure',
    lessonCount: 10,
    overview:
      'Learn in the browser without installing development tools. Use Android Studio when your team is ready to build and deploy code to a physical robot, and return to the simulator if local setup blocks your progress.',
    outcomes: [
      'Use Telemark lessons and simulators without installing local development software.',
      'Treat Android Studio as an optional head start for joining an advanced team, not a requirement for learning Java.',
      'Return to the built-in simulator if Android Studio installation or configuration causes serious issues.',
      'Build a diagnostic OpMode and connect to the Robot Controller when hardware is available.',
    ],
  },
  {
    id: 'UNIT_02',
    label: 'Unit 2',
    title: 'OpMode Structure',
    desc: 'Learn annotations and the FTC OpMode lifecycle.',
    tier: 'Beginner',
    slug: 'unit-02',
    overviewPath: '/docs/unit-02',
    startPath: '/docs/unit-02/registering-programs',
    nextPath: '/docs/unit-03',
    nextLabel: 'Unit 3: Java Variables',
    lessonCount: 7,
    overview:
      'Map the FTC OpMode lifecycle so you know where setup, repeated control logic, and one-time transitions belong.',
    outcomes: [
      'Choose the right annotation so programs appear correctly on the Driver Station.',
      'Separate setup work from repeated loop logic and one-time start/stop transitions.',
      'Build a health-check style OpMode that reports robot state clearly through telemetry.',
    ],
  },
  {
    id: 'UNIT_03',
    label: 'Unit 3',
    title: 'Java Variables',
    desc: 'Use Java variables and datatypes in robot code.',
    tier: 'Beginner',
    slug: 'unit-03',
    overviewPath: '/docs/unit-03',
    startPath: '/docs/unit-03/string-literals',
    nextPath: '/docs/unit-04',
    nextLabel: 'Unit 4: Gamepad Input',
    lessonCount: 10,
    overview:
      'Use the Java data types that appear throughout FTC code, including hardware names, sensor readings, control values, and counters.',
    outcomes: [
      'Choose the correct datatype for names, numeric precision, binary state, and whole-number counts.',
      'Avoid common FTC bugs caused by integer truncation or mismatched hardware identifiers.',
      'Use variables as a single source of truth instead of scattering magic values through code.',
    ],
  },
  {
    id: 'UNIT_04',
    label: 'Unit 4',
    title: 'Gamepad Input',
    desc: 'Turn buttons, sticks, and triggers into stable controls.',
    tier: 'Beginner',
    slug: 'unit-04',
    overviewPath: '/docs/unit-04',
    startPath: '/docs/unit-04/button-toggles',
    nextPath: '/docs/unit-05',
    nextLabel: 'Unit 5: Logic & Decisions',
    lessonCount: 6,
    overview:
      'Turn driver input into predictable robot behavior with button toggles, joystick scaling, trigger controls, and sensitivity curves.',
    outcomes: [
      'Use buttons, joysticks, and triggers appropriately based on whether the mechanism needs digital or analog control.',
      'Implement deadzones and sensitivity shaping so the robot feels stable and intuitive to drive.',
      'Combine multiple gamepad inputs into a clean arcade-drive style control system.',
    ],
  },
  {
    id: 'UNIT_05',
    label: 'Unit 5',
    title: 'Logic & Decisions',
    desc: 'Use conditions and comparisons to control robot behavior safely.',
    tier: 'Beginner',
    slug: 'unit-05',
    overviewPath: '/docs/unit-05',
    startPath: '/docs/unit-05/if-statements',
    nextPath: '/docs/unit-06',
    nextLabel: 'Unit 6: Loops & Iteration',
    lessonCount: 6,
    overview:
      'Use conditions and comparisons to handle button checks, mechanism limits, and multi-sensor automation safely.',
    outcomes: [
      'Use if/else if/else chains to guarantee a single unambiguous command reaches hardware each loop cycle.',
      'Implement comparison operators to create soft-limit safety zones that prevent motors from exceeding physical bounds.',
      'Combine multiple sensor thresholds with logical AND/OR operators for robust, driver-verified hardware actions.',
    ],
  },
  {
    id: 'UNIT_06',
    label: 'Unit 6',
    title: 'Loops & Iteration',
    desc: 'Use loops, arrays, and timers without blocking robot control.',
    tier: 'Intermediate',
    slug: 'unit-06',
    overviewPath: '/docs/unit-06',
    startPath: '/docs/unit-06/opmode-active',
    nextPath: '/docs/unit-07',
    nextLabel: 'Unit 7: Hardware Mapping',
    lessonCount: 6,
    overview:
      'Write repeated actions, timed behavior, and multi-device commands without blocking the rest of the robot.',
    outcomes: [
      'Use loop-based control structures safely so code stops when the OpMode stops.',
      'Automate repeated actions and multi-device commands with for loops and array iteration.',
      'Build timer-based behavior that runs in parallel without freezing the rest of the robot.',
    ],
  },
  {
    id: 'UNIT_07',
    label: 'Unit 7',
    title: 'Hardware Mapping',
    desc: 'Map configured hardware and organize reusable mechanism classes.',
    tier: 'Intermediate',
    slug: 'unit-07',
    overviewPath: '/docs/unit-07',
    startPath: '/docs/unit-07/hardware-map-object',
    nextPath: '/docs/unit-08',
    nextLabel: 'Unit 8: DC Motor Control',
    lessonCount: 6,
    overview:
      'Connect FTC configuration names to Java objects, then organize motors, sensors, and mechanisms so every OpMode uses them consistently.',
    outcomes: [
      'Use the hardwareMap registry to retrieve configured devices with the correct Java class and exact robot configuration name.',
      'Map motors and sensors consistently while diagnosing name mismatches and configuration overlay problems quickly.',
      'Organize shared mechanism code into reusable classes that stay synchronized across multiple OpModes.',
    ],
  },
  {
    id: 'UNIT_08',
    label: 'Unit 8',
    title: 'DC Motor Control',
    desc: 'Control motor power, direction, braking, and motion limits.',
    tier: 'Intermediate',
    slug: 'unit-08',
    overviewPath: '/docs/unit-08',
    startPath: '/docs/unit-08/set-power',
    nextPath: '/docs/unit-09',
    nextLabel: 'Unit 9: Servo Control',
    lessonCount: 6,
    overview:
      'Control mapped motors with intentional power, direction, braking, and software limits so mechanisms move and stop as expected.',
    outcomes: [
      'Apply motor power intentionally with setPower() so mechanisms move at the right speed and stop when expected.',
      'Correct mechanical orientation issues with setDirection() and choose between coasting and braking behavior deliberately.',
      'Build safer motor routines with zero-power handling and software-enforced motion limits for mechanisms like linear slides.',
    ],
  },
  {
    id: 'UNIT_09',
    label: 'Unit 9',
    title: 'Servo Control',
    desc: 'Control positional and continuous-rotation servos.',
    tier: 'Intermediate',
    slug: 'unit-09',
    overviewPath: '/docs/unit-09',
    startPath: '/docs/unit-09/set-position',
    nextPath: '/docs/unit-10',
    nextLabel: 'Unit 10: Encoders & Precision',
    lessonCount: 6,
    overview:
      'Control positional and continuous-rotation servos without overdriving linkages or confusing their different command models.',
    outcomes: [
      'Use setPosition() and scaleRange() to command positional servos without overdriving physical linkages.',
      'Configure mirrored mechanisms cleanly with servo direction settings instead of duplicating inversion math across OpModes.',
      'Choose correctly between Servo and CRServo so intake and gripper mechanisms use the right control model.',
    ],
  },
  {
    id: 'UNIT_10',
    label: 'Unit 10',
    title: 'Encoders & Precision',
    desc: 'Turn encoder ticks into measured autonomous movement.',
    tier: 'Intermediate',
    slug: 'unit-10',
    overviewPath: '/docs/unit-10',
    startPath: '/docs/unit-10/get-current-position',
    nextPath: '/docs/unit-11',
    nextLabel: 'Unit 11: Digital & Analog Sensors',
    lessonCount: 6,
    overview:
      'Use encoder feedback to measure autonomous movement, convert ticks to distance, and choose the correct motor run mode.',
    outcomes: [
      'Read encoder tick counts and understand how they relate to real motor rotation.',
      'Convert ticks into meaningful distances using ticks-per-revolution data and wheel geometry.',
      'Choose between RUN_TO_POSITION, RUN_USING_ENCODER, and encoder resets for more reliable autonomous control.',
    ],
  },
  {
    id: 'UNIT_11',
    label: 'Unit 11',
    title: 'Digital & Analog Sensors',
    desc: 'Read digital, analog, color, and distance sensors.',
    tier: 'Intermediate',
    slug: 'unit-11',
    overviewPath: '/docs/unit-11',
    startPath: '/docs/unit-11/touch-sensor',
    nextPath: '/docs/unit-12',
    nextLabel: 'Unit 12: IMU & Rotation',
    lessonCount: 6,
    overview:
      'Read, scale, and respond to digital, analog, color, and distance sensors used on FTC robots.',
    outcomes: [
      'Read digital touch sensors correctly, accounting for active-low hardware logic, and use them as reliable software limit switches.',
      'Convert raw potentiometer voltage into engineering units using Range.scale() for absolute positional feedback without a homing sequence.',
      'Sample and compare color sensor channels to identify alliance game elements reliably across different field lighting conditions.',
    ],
  },
  {
    id: 'UNIT_12',
    label: 'Unit 12',
    title: 'IMU & Rotation',
    desc: 'Use the IMU for heading, field-centric drive, and turning.',
    tier: 'Intermediate',
    slug: 'unit-12',
    overviewPath: '/docs/unit-12',
    startPath: '/docs/unit-12/imu-initialization',
    nextPath: '/docs/unit-13',
    nextLabel: 'Unit 13: OOP & Inheritance',
    lessonCount: 6,
    overview:
      'Use the REV Hub IMU for heading, field-centric control, tilt monitoring, and closed-loop autonomous turns.',
    outcomes: [
      'Initialize the IMU correctly for any physical Hub mounting orientation using RevHubOrientationOnRobot.',
      'Read and normalize Yaw, Pitch, and Roll data using the AngleUnit class for reliable heading and tilt feedback.',
      'Implement field-centric driving and IMU-corrected proportional autonomous turns that self-correct for battery drop and wheel slip.',
    ],
  },
  {
    id: 'UNIT_13',
    label: 'Unit 13',
    title: 'OOP & Inheritance',
    desc: 'Organize robot code with classes, inheritance, and composition.',
    tier: 'Advanced',
    slug: 'unit-13',
    overviewPath: '/docs/unit-13',
    startPath: '/docs/unit-13/encapsulation',
    nextPath: '/docs/unit-14',
    nextLabel: 'Unit 14: Computer Vision',
    lessonCount: 10,
    overview:
      'Structure competition code with encapsulation, inheritance, and composition so mechanisms can be reused and hardware changes stay contained.',
    outcomes: [
      'Encapsulate mechanism hardware and logic into private-member classes with clean public interfaces, eliminating duplicated code across OpModes.',
      'Apply inheritance and @Override to build a family of specialized mechanisms from a shared parent, with the compiler enforcing correct implementation.',
      'Build Intake, Lift, RobotHardware, and CompetitionTeleOp as a reusable multi-file project for TeleOp and autonomous.',
    ],
  },
  {
    id: 'UNIT_14',
    label: 'Unit 14',
    title: 'Computer Vision',
    desc: 'Use VisionPortal, AprilTags, and OpenCV analysis zones.',
    tier: 'Advanced',
    slug: 'unit-14',
    overviewPath: '/docs/unit-14',
    startPath: '/docs/unit-14/vision-portal',
    nextPath: '/docs/unit-15',
    nextLabel: 'Unit 15: Advanced Integration',
    lessonCount: 6,
    overview:
      'Use the FTC Vision SDK to configure a camera, read AprilTags, and classify scoring locations with OpenCV zones.',
    outcomes: [
      'Configure a VisionPortal, attach processors, and manage the camera stream lifecycle to preserve CPU resources during the driving phase.',
      'Detect and iterate over AprilTag detections safely, extracting pose data to implement closed-loop vision-based robot alignment.',
      'Build a custom VisionProcessor using OpenCV Rect zones and HSV saturation comparison to identify game element spike mark locations reliably across varying competition lighting.',
    ],
  },
  {
    id: 'UNIT_15',
    label: 'Unit 15',
    title: 'Advanced Integration',
    desc: 'Combine vision, localization, Pedro 3 pathing, and Ivy command control.',
    tier: 'Advanced',
    slug: 'unit-15',
    overviewPath: '/docs/unit-15',
    startPath: '/docs/unit-15/limelight',
    nextPath: '/dashboard',
    nextLabel: 'Dashboard',
    lessonCount: 6,
    overview:
      'Combine vision, localization, Pedro 3 path following, and Ivy commands into a complete autonomous routine.',
    outcomes: [
      'Use the Limelight 3A to run dedicated vision pipelines and retrieve validated targeting data from robot code.',
      'Build smooth autonomous trajectories with Pedro 3 line(), curve(), and compound Path APIs.',
      'Fuse AprilTag-based global pose corrections with odometry and coordinate full routines using non-blocking Ivy commands.',
    ],
  },
];

export const CURRICULUM_LESSONS: CurriculumLesson[] = [
  {
    id: 'unit-00/classes-and-objects',
    label: '0.1 · Classes & Objects',
    title: 'Lesson 0.1: Classes, and Objects',
    path: '/docs/unit-00/classes-and-objects',
    unitSlug: 'unit-00',
    unitLabel: 'Unit 0',
    unitTitle: 'Objects, Classes, and Java',
  },
  {
    id: 'unit-00/how-java-runs',
    label: '0.2 · Fields, Constructors & Methods',
    title: 'Lesson 0.2: Fields, Constructors, and Methods',
    path: '/docs/unit-00/fields-constructors-methods',
    unitSlug: 'unit-00',
    unitLabel: 'Unit 0',
    unitTitle: 'Objects, Classes, and Java',
  },
  {
    id: 'unit-00/references-and-identity',
    label: '0.3 · References & Identity',
    title: 'Lesson 0.3: References and Object Identity',
    path: '/docs/unit-00/references-and-identity',
    unitSlug: 'unit-00',
    unitLabel: 'Unit 0',
    unitTitle: 'Objects, Classes, and Java',
  },
  {
    id: 'unit-00/objects-working-together',
    label: '0.4 · Objects Working Together',
    title: 'Lesson 0.4: How Objects Work Together',
    path: '/docs/unit-00/objects-working-together',
    unitSlug: 'unit-00',
    unitLabel: 'Unit 0',
    unitTitle: 'Objects, Classes, and Java',
  },
  {
    id: 'unit-00/static-and-nested-members',
    label: '0.5 · Instance, Static & Nested',
    title: 'Lesson 0.5: Instance, Static, and Nested Members',
    path: '/docs/unit-00/static-and-nested-members',
    unitSlug: 'unit-00',
    unitLabel: 'Unit 0',
    unitTitle: 'Objects, Classes, and Java',
  },
  {
    id: 'unit-01/prerequisites',
    label: '1 · Prerequisites',
    title: 'Section 1: What to Have Ready Before You Start',
    path: '/docs/unit-01/prerequisites',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-01/install-jdk',
    label: '2 · Java Versions (Optional)',
    title: 'Section 2: Understanding Java Versions for Android Studio',
    path: '/docs/unit-01/install-jdk',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-01/install-android-studio',
    label: '3 · Android Studio (Optional)',
    title: 'Section 3: Installing Android Studio for FTC',
    path: '/docs/unit-01/install-android-studio',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-01/configure-jdk',
    label: '4 · Check Gradle JDK',
    title: "Section 4: Checking Android Studio's Gradle JDK",
    path: '/docs/unit-01/configure-jdk',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-01/get-ftc-sdk',
    label: '5 · Getting the FTC SDK',
    title: 'Section 5: Downloading the FTC SDK',
    path: '/docs/unit-01/get-ftc-sdk',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-01/open-project',
    label: '6 · Open the Project',
    title: 'Section 6: Opening the FTC Project in Android Studio',
    path: '/docs/unit-01/open-project',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-01/verify-build-config',
    label: '7 · Verify Build Config',
    title: 'Section 7: Checking That the Build Setup Works',
    path: '/docs/unit-01/verify-build-config',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-01/first-opmode',
    label: '8 · First OpMode',
    title: 'Section 8: Writing Your First FTC OpMode',
    path: '/docs/unit-01/first-opmode',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-01/connect-control-hub',
    label: '9 · Connect to Control Hub',
    title: 'Section 9: Connecting Your Programming Tool to the Control Hub',
    path: '/docs/unit-01/connect-control-hub',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-01/verification-checklist',
    label: '10 · Verification Checklist',
    title: 'Section 10: Final Environment Setup Check',
    path: '/docs/unit-01/verification-checklist',
    unitSlug: 'unit-01',
    unitLabel: 'Unit 1',
    unitTitle: 'Environment Setup',
  },
  {
    id: 'unit-02/registering-programs',
    label: '2.1 · @TeleOp & @Autonomous',
    title: 'Lesson 2.1: Getting Your OpModes to Show Up with @TeleOp and @Autonomous',
    path: '/docs/unit-02/registering-programs',
    unitSlug: 'unit-02',
    unitLabel: 'Unit 2',
    unitTitle: 'OpMode Structure',
  },
  {
    id: 'unit-02/init-method',
    label: '2.2 · init() Method',
    title: 'Lesson 2.2: Setting Up Hardware in init() Before the Match Starts',
    path: '/docs/unit-02/init-method',
    unitSlug: 'unit-02',
    unitLabel: 'Unit 2',
    unitTitle: 'OpMode Structure',
  },
  {
    id: 'unit-02/loop-lifecycle',
    label: '2.3 · loop() Lifecycle',
    title: 'Lesson 2.3: Running Real-Time Robot Logic Inside loop()',
    path: '/docs/unit-02/loop-lifecycle',
    unitSlug: 'unit-02',
    unitLabel: 'Unit 2',
    unitTitle: 'OpMode Structure',
  },
  {
    id: 'unit-02/start-and-stop',
    label: '2.4 · start() & stop()',
    title: 'Lesson 2.4: Using start() and stop() for One-Time Robot Actions',
    path: '/docs/unit-02/start-and-stop',
    unitSlug: 'unit-02',
    unitLabel: 'Unit 2',
    unitTitle: 'OpMode Structure',
  },
  {
    id: 'unit-02/health-check-challenge',
    label: '2.5 · Robot Health-Check',
    title: 'Lesson 2.5: Build a Robot Health-Check OpMode with Telemetry',
    path: '/docs/unit-02/health-check-challenge',
    unitSlug: 'unit-02',
    unitLabel: 'Unit 2',
    unitTitle: 'OpMode Structure',
  },
  {
    id: 'unit-02/choosing-opmode-type',
    label: '2.6 · Choosing OpMode Type',
    title: 'Lesson 2.6: Choosing Your OpMode Type',
    path: '/docs/unit-02/choosing-opmode-type',
    unitSlug: 'unit-02',
    unitLabel: 'Unit 2',
    unitTitle: 'OpMode Structure',
  },
  {
    id: 'unit-02/mastery-coding-challenge',
    label: 'Unit 2 · Coding Challenge',
    title: 'Unit 2 Comprehensive Coding Challenge: Complete OpMode Lifecycle',
    path: '/docs/unit-02/mastery-coding-challenge',
    unitSlug: 'unit-02',
    unitLabel: 'Unit 2',
    unitTitle: 'OpMode Structure',
  },
  {
    id: 'unit-03/string-literals',
    label: '3.1 · String Literals',
    title: 'Lesson 3.1: Using Strings to Match Hardware Names Exactly',
    path: '/docs/unit-03/string-literals',
    unitSlug: 'unit-03',
    unitLabel: 'Unit 3',
    unitTitle: 'Java Variables',
  },
  {
    id: 'unit-03/double-precision',
    label: '3.2 · double Precision',
    title: 'Lesson 3.2: Using double for Motor Power and Precise Math',
    path: '/docs/unit-03/double-precision',
    unitSlug: 'unit-03',
    unitLabel: 'Unit 3',
    unitTitle: 'Java Variables',
  },
  {
    id: 'unit-03/boolean-flags',
    label: '3.3 · boolean Flags',
    title: 'Lesson 3.3: Using boolean Values for On-or-Off Robot State',
    path: '/docs/unit-03/boolean-flags',
    unitSlug: 'unit-03',
    unitLabel: 'Unit 3',
    unitTitle: 'Java Variables',
  },
  {
    id: 'unit-03/int-datatypes',
    label: '3.4 · int Datatypes',
    title: 'Lesson 3.4: Using int Values to Count Cycles and Repetitions',
    path: '/docs/unit-03/int-datatypes',
    unitSlug: 'unit-03',
    unitLabel: 'Unit 3',
    unitTitle: 'Java Variables',
  },
  {
    id: 'unit-03/dynamic-power-challenge',
    label: '3.5 · Dynamic Power',
    title: 'Lesson 3.5: Build Dynamic Power Logic with Multiple Variables',
    path: '/docs/unit-03/dynamic-power-challenge',
    unitSlug: 'unit-03',
    unitLabel: 'Unit 3',
    unitTitle: 'Java Variables',
  },
  {
    id: 'unit-03/mastery-coding-challenge',
    label: 'Unit 3 · Coding Challenge',
    title: 'Unit 3 Comprehensive Coding Challenge: Robot State Variables',
    path: '/docs/unit-03/mastery-coding-challenge',
    unitSlug: 'unit-03',
    unitLabel: 'Unit 3',
    unitTitle: 'Java Variables',
  },
  {
    id: 'unit-04/button-toggles',
    label: '4.1 · Button Toggles',
    title: 'Lesson 4.1: Mapping gamepad Buttons to Simple Mechanism Toggles',
    path: '/docs/unit-04/button-toggles',
    unitSlug: 'unit-04',
    unitLabel: 'Unit 4',
    unitTitle: 'Gamepad Input',
  },
  {
    id: 'unit-04/joystick-scaling',
    label: '4.2 · Joystick Scaling',
    title: 'Lesson 4.2: Turning Joystick X and Y into Smooth Drive Control',
    path: '/docs/unit-04/joystick-scaling',
    unitSlug: 'unit-04',
    unitLabel: 'Unit 4',
    unitTitle: 'Gamepad Input',
  },
  {
    id: 'unit-04/trigger-inputs',
    label: '4.3 · Trigger Inputs',
    title: 'Lesson 4.3: Using Triggers for Gradual Braking Control',
    path: '/docs/unit-04/trigger-inputs',
    unitSlug: 'unit-04',
    unitLabel: 'Unit 4',
    unitTitle: 'Gamepad Input',
  },
  {
    id: 'unit-04/sensitivity-curves',
    label: '4.4 · Sensitivity Curves',
    title: 'Lesson 4.4: Shaping Joystick Sensitivity with squareInputWithSign()',
    path: '/docs/unit-04/sensitivity-curves',
    unitSlug: 'unit-04',
    unitLabel: 'Unit 4',
    unitTitle: 'Gamepad Input',
  },
  {
    id: 'unit-04/arcade-drive-challenge',
    label: '4.5 · Arcade Drive',
    title: 'Lesson 4.5: Build a Complete Arcade Drive',
    path: '/docs/unit-04/arcade-drive-challenge',
    unitSlug: 'unit-04',
    unitLabel: 'Unit 4',
    unitTitle: 'Gamepad Input',
  },
  {
    id: 'unit-04/mastery-coding-challenge',
    label: 'Unit 4 · Coding Challenge',
    title: 'Unit 4 Comprehensive Coding Challenge: Driver-Controlled Drivetrain',
    path: '/docs/unit-04/mastery-coding-challenge',
    unitSlug: 'unit-04',
    unitLabel: 'Unit 4',
    unitTitle: 'Gamepad Input',
  },
  {
    id: 'unit-05/if-statements',
    label: '5.1 · if Statements',
    title: 'Lesson 5.1: Using if Statements to Decide When a Motor Should Run',
    path: '/docs/unit-05/if-statements',
    unitSlug: 'unit-05',
    unitLabel: 'Unit 5',
    unitTitle: 'Logic & Decisions',
  },
  {
    id: 'unit-05/else-if-chaining',
    label: '5.2 · else if Chaining',
    title: 'Lesson 5.2: Using else if Chains to Pick One Robot Action at a Time',
    path: '/docs/unit-05/else-if-chaining',
    unitSlug: 'unit-05',
    unitLabel: 'Unit 5',
    unitTitle: 'Logic & Decisions',
  },
  {
    id: 'unit-05/comparison-operators',
    label: '5.3 · Comparison Operators',
    title: 'Lesson 5.3: Using Comparison Operators to Protect Hardware Limits',
    path: '/docs/unit-05/comparison-operators',
    unitSlug: 'unit-05',
    unitLabel: 'Unit 5',
    unitTitle: 'Logic & Decisions',
  },
  {
    id: 'unit-05/logical-operators',
    label: '5.4 · Logical Operators',
    title: 'Lesson 5.4: Combining Sensor Checks with AND and OR Logic',
    path: '/docs/unit-05/logical-operators',
    unitSlug: 'unit-05',
    unitLabel: 'Unit 5',
    unitTitle: 'Logic & Decisions',
  },
  {
    id: 'unit-05/intake-logic-challenge',
    label: '5.5 · Intake Logic',
    title: 'Lesson 5.5: Build Intake Logic for Multi-Stage Game Piece Sorting',
    path: '/docs/unit-05/intake-logic-challenge',
    unitSlug: 'unit-05',
    unitLabel: 'Unit 5',
    unitTitle: 'Logic & Decisions',
  },
  {
    id: 'unit-05/mastery-coding-challenge',
    label: 'Unit 5 · Coding Challenge',
    title: 'Unit 5 Comprehensive Coding Challenge: Safe Intake Decision Tree',
    path: '/docs/unit-05/mastery-coding-challenge',
    unitSlug: 'unit-05',
    unitLabel: 'Unit 5',
    unitTitle: 'Logic & Decisions',
  },
  {
    id: 'unit-06/opmode-active',
    label: '6.1 · opModeIsActive()',
    title: 'Lesson 6.1: Keeping a LinearOpMode Safe with while(opModeIsActive())',
    path: '/docs/unit-06/opmode-active',
    unitSlug: 'unit-06',
    unitLabel: 'Unit 6',
    unitTitle: 'Loops & Iteration',
  },
  {
    id: 'unit-06/for-loops',
    label: '6.2 · for Loops',
    title: 'Lesson 6.2: Using for Loops to Repeat Robot Actions Cleanly',
    path: '/docs/unit-06/for-loops',
    unitSlug: 'unit-06',
    unitLabel: 'Unit 6',
    unitTitle: 'Loops & Iteration',
  },
  {
    id: 'unit-06/runtime-timing',
    label: '6.3 · getRuntime() Timing',
    title: 'Lesson 6.3: Timing Robot Actions with getRuntime()',
    path: '/docs/unit-06/runtime-timing',
    unitSlug: 'unit-06',
    unitLabel: 'Unit 6',
    unitTitle: 'Loops & Iteration',
  },
  {
    id: 'unit-06/hardware-arrays',
    label: '6.4 · Hardware Arrays',
    title: 'Lesson 6.4: Looping Through Hardware Arrays with for-each',
    path: '/docs/unit-06/hardware-arrays',
    unitSlug: 'unit-06',
    unitLabel: 'Unit 6',
    unitTitle: 'Loops & Iteration',
  },
  {
    id: 'unit-06/nonblocking-timer',
    label: '6.5 · Non-Blocking Timer',
    title: 'Lesson 6.5: Build a Non-Blocking Timer for Parallel Mechanism Control',
    path: '/docs/unit-06/nonblocking-timer',
    unitSlug: 'unit-06',
    unitLabel: 'Unit 6',
    unitTitle: 'Loops & Iteration',
  },
  {
    id: 'unit-06/mastery-coding-challenge',
    label: 'Unit 6 · Coding Challenge',
    title: 'Unit 6 Comprehensive Coding Challenge: Non-Blocking Autonomous Loop',
    path: '/docs/unit-06/mastery-coding-challenge',
    unitSlug: 'unit-06',
    unitLabel: 'Unit 6',
    unitTitle: 'Loops & Iteration',
  },
  {
    id: 'unit-07/hardware-map-object',
    label: '7.1 · hardwareMap Object',
    title: 'Lesson 7.1: Using hardwareMap to Find the Devices You Configured',
    path: '/docs/unit-07/hardware-map-object',
    unitSlug: 'unit-07',
    unitLabel: 'Unit 7',
    unitTitle: 'Hardware Mapping',
  },
  {
    id: 'unit-07/dcmotor-mapping',
    label: '7.2 · DcMotor Mapping',
    title: 'Lesson 7.2: Mapping DcMotors with the Right Names and Ports',
    path: '/docs/unit-07/dcmotor-mapping',
    unitSlug: 'unit-07',
    unitLabel: 'Unit 7',
    unitTitle: 'Hardware Mapping',
  },
  {
    id: 'unit-07/sensor-mapping',
    label: '7.3 · Sensor Mapping',
    title: 'Lesson 7.3: Mapping Digital and Analog Sensors into Java Objects',
    path: '/docs/unit-07/sensor-mapping',
    unitSlug: 'unit-07',
    unitLabel: 'Unit 7',
    unitTitle: 'Hardware Mapping',
  },
  {
    id: 'unit-07/name-mismatches',
    label: '7.4 · Name Mismatches',
    title: 'Lesson 7.4: Debugging Name Mismatches and Configuration Problems',
    path: '/docs/unit-07/name-mismatches',
    unitSlug: 'unit-07',
    unitLabel: 'Unit 7',
    unitTitle: 'Hardware Mapping',
  },
  {
    id: 'unit-07/mechanism-classes',
    label: '7.5 · Mechanism Classes',
    title: 'Lesson 7.5: Keep Shared Hardware Classes Consistent Across OpModes',
    path: '/docs/unit-07/mechanism-classes',
    unitSlug: 'unit-07',
    unitLabel: 'Unit 7',
    unitTitle: 'Hardware Mapping',
  },
  {
    id: 'unit-07/mastery-coding-challenge',
    label: 'Unit 7 · Coding Challenge',
    title: 'Unit 7 Comprehensive Coding Challenge: Reusable Hardware Subsystem',
    path: '/docs/unit-07/mastery-coding-challenge',
    unitSlug: 'unit-07',
    unitLabel: 'Unit 7',
    unitTitle: 'Hardware Mapping',
  },
  {
    id: 'unit-08/set-power',
    label: '8.1 · setPower()',
    title: 'Lesson 8.1: Using setPower() to Control Motor Speed',
    path: '/docs/unit-08/set-power',
    unitSlug: 'unit-08',
    unitLabel: 'Unit 8',
    unitTitle: 'DC Motor Control',
  },
  {
    id: 'unit-08/set-direction',
    label: '8.2 · Mecanum Direction',
    title: 'Lesson 8.2: Configure Mecanum Motor Direction and Wheel Mixing',
    path: '/docs/unit-08/set-direction',
    unitSlug: 'unit-08',
    unitLabel: 'Unit 8',
    unitTitle: 'DC Motor Control',
  },
  {
    id: 'unit-08/zero-power-behavior',
    label: '8.3 · ZeroPowerBehavior',
    title: 'Lesson 8.3: Using ZeroPowerBehavior.BRAKE to Hold Position Better',
    path: '/docs/unit-08/zero-power-behavior',
    unitSlug: 'unit-08',
    unitLabel: 'Unit 8',
    unitTitle: 'DC Motor Control',
  },
  {
    id: 'unit-08/coast-vs-stop',
    label: '8.4 · Coast vs. Stop',
    title: 'Lesson 8.4: Choosing Between Coasting and Stopping with setPower(0.0)',
    path: '/docs/unit-08/coast-vs-stop',
    unitSlug: 'unit-08',
    unitLabel: 'Unit 8',
    unitTitle: 'DC Motor Control',
  },
  {
    id: 'unit-08/linear-slide-challenge',
    label: '8.5 · Linear Slide',
    title: 'Lesson 8.5: Build a Two-Way Linear Slide with Software Limits',
    path: '/docs/unit-08/linear-slide-challenge',
    unitSlug: 'unit-08',
    unitLabel: 'Unit 8',
    unitTitle: 'DC Motor Control',
  },
  {
    id: 'unit-08/mastery-coding-challenge',
    label: 'Unit 8 · Coding Challenge',
    title: 'Unit 8 Comprehensive Coding Challenge: Limit-Safe Linear Slide',
    path: '/docs/unit-08/mastery-coding-challenge',
    unitSlug: 'unit-08',
    unitLabel: 'Unit 8',
    unitTitle: 'DC Motor Control',
  },
  {
    id: 'unit-09/set-position',
    label: '9.1 · setPosition()',
    title: 'Lesson 9.1: Using setPosition() for Accurate Servo Movement',
    path: '/docs/unit-09/set-position',
    unitSlug: 'unit-09',
    unitLabel: 'Unit 9',
    unitTitle: 'Servo Control',
  },
  {
    id: 'unit-09/scale-range',
    label: '9.2 · scaleRange()',
    title: 'Lesson 9.2: Limiting Servo Travel Safely with scaleRange()',
    path: '/docs/unit-09/scale-range',
    unitSlug: 'unit-09',
    unitLabel: 'Unit 9',
    unitTitle: 'Servo Control',
  },
  {
    id: 'unit-09/servo-direction',
    label: '9.3 · Servo Direction',
    title: 'Lesson 9.3: Fixing Inverted Servo Setups with Direction Settings',
    path: '/docs/unit-09/servo-direction',
    unitSlug: 'unit-09',
    unitLabel: 'Unit 9',
    unitTitle: 'Servo Control',
  },
  {
    id: 'unit-09/cr-servo',
    label: '9.4 · CRServo',
    title: 'Lesson 9.4: Using CRServos for Intake-Style Mechanisms',
    path: '/docs/unit-09/cr-servo',
    unitSlug: 'unit-09',
    unitLabel: 'Unit 9',
    unitTitle: 'Servo Control',
  },
  {
    id: 'unit-09/dual-servo-challenge',
    label: '9.5 · Dual-Servo Gripper',
    title: 'Lesson 9.5: Sync a Dual-Servo Gripper with Offset Tuning',
    path: '/docs/unit-09/dual-servo-challenge',
    unitSlug: 'unit-09',
    unitLabel: 'Unit 9',
    unitTitle: 'Servo Control',
  },
  {
    id: 'unit-09/mastery-coding-challenge',
    label: 'Unit 9 · Coding Challenge',
    title: 'Unit 9 Comprehensive Coding Challenge: Coordinated Servo Mechanism',
    path: '/docs/unit-09/mastery-coding-challenge',
    unitSlug: 'unit-09',
    unitLabel: 'Unit 9',
    unitTitle: 'Servo Control',
  },
  {
    id: 'unit-10/get-current-position',
    label: '10.1 · getCurrentPosition()',
    title: 'Lesson 10.1: Reading Raw Tick Counts with getCurrentPosition()',
    path: '/docs/unit-10/get-current-position',
    unitSlug: 'unit-10',
    unitLabel: 'Unit 10',
    unitTitle: 'Encoders & Precision',
  },
  {
    id: 'unit-10/ticks-to-distance',
    label: '10.2 · Ticks to Distance',
    title: 'Lesson 10.2: Calculating Distances based on Ticks Per Revolution Data',
    path: '/docs/unit-10/ticks-to-distance',
    unitSlug: 'unit-10',
    unitLabel: 'Unit 10',
    unitTitle: 'Encoders & Precision',
  },
  {
    id: 'unit-10/run-to-position',
    label: '10.3 · RUN_TO_POSITION',
    title: 'Lesson 10.3: Automating Targeted Movement with RUN_TO_POSITION',
    path: '/docs/unit-10/run-to-position',
    unitSlug: 'unit-10',
    unitLabel: 'Unit 10',
    unitTitle: 'Encoders & Precision',
  },
  {
    id: 'unit-10/run-using-encoder',
    label: '10.4 · RUN_USING_ENCODER',
    title: 'Lesson 10.4: Maintaining Speed Consistency with RUN_USING_ENCODER',
    path: '/docs/unit-10/run-using-encoder',
    unitSlug: 'unit-10',
    unitLabel: 'Unit 10',
    unitTitle: 'Encoders & Precision',
  },
  {
    id: 'unit-10/drive-and-stop',
    label: '10.5 · Drive and Stop',
    title: 'Lesson 10.5: Developing a Precise Drive and Stop System for Linear Navigation',
    path: '/docs/unit-10/drive-and-stop',
    unitSlug: 'unit-10',
    unitLabel: 'Unit 10',
    unitTitle: 'Encoders & Precision',
  },
  {
    id: 'unit-10/mastery-coding-challenge',
    label: 'Unit 10 · Coding Challenge',
    title: 'Unit 10 Comprehensive Coding Challenge: Encoder Distance Autonomous',
    path: '/docs/unit-10/mastery-coding-challenge',
    unitSlug: 'unit-10',
    unitLabel: 'Unit 10',
    unitTitle: 'Encoders & Precision',
  },
  {
    id: 'unit-11/touch-sensor',
    label: '11.1 · Touch Sensor',
    title: 'Lesson 11.1: Reading Touch Sensor Binary States via DigitalChannel',
    path: '/docs/unit-11/touch-sensor',
    unitSlug: 'unit-11',
    unitLabel: 'Unit 11',
    unitTitle: 'Digital & Analog Sensors',
  },
  {
    id: 'unit-11/potentiometer',
    label: '11.2 · Potentiometer',
    title: 'Lesson 11.2: Scaling Analog Voltage from Potentiometers using Range.scale',
    path: '/docs/unit-11/potentiometer',
    unitSlug: 'unit-11',
    unitLabel: 'Unit 11',
    unitTitle: 'Digital & Analog Sensors',
  },
  {
    id: 'unit-11/color-sensor',
    label: '11.3 · Color Sensor',
    title: 'Lesson 11.3: Sampling Alliance Colors with the REV Color Sensor',
    path: '/docs/unit-11/color-sensor',
    unitSlug: 'unit-11',
    unitLabel: 'Unit 11',
    unitTitle: 'Digital & Analog Sensors',
  },
  {
    id: 'unit-11/distance-sensor',
    label: '11.4 · Distance Sensor',
    title: 'Lesson 11.4: Integration of Time-of-Flight Distance Sensors for Obstacle Detection',
    path: '/docs/unit-11/distance-sensor',
    unitSlug: 'unit-11',
    unitLabel: 'Unit 11',
    unitTitle: 'Digital & Analog Sensors',
  },
  {
    id: 'unit-11/sensor-gated-intake',
    label: '11.5 · Sensor-Gated Intake',
    title: 'Lesson 11.5: Creating an Automated Sensor-Gated Intake System',
    path: '/docs/unit-11/sensor-gated-intake',
    unitSlug: 'unit-11',
    unitLabel: 'Unit 11',
    unitTitle: 'Digital & Analog Sensors',
  },
  {
    id: 'unit-11/mastery-coding-challenge',
    label: 'Unit 11 · Coding Challenge',
    title: 'Unit 11 Comprehensive Coding Challenge: Multi-Sensor Intake',
    path: '/docs/unit-11/mastery-coding-challenge',
    unitSlug: 'unit-11',
    unitLabel: 'Unit 11',
    unitTitle: 'Digital & Analog Sensors',
  },
  {
    id: 'unit-12/imu-initialization',
    label: '12.1 · IMU Initialization',
    title: 'Lesson 12.1: Initializing the REV Hub Gyro and Setting Robot Orientation',
    path: '/docs/unit-12/imu-initialization',
    unitSlug: 'unit-12',
    unitLabel: 'Unit 12',
    unitTitle: 'IMU & Rotation',
  },
  {
    id: 'unit-12/yaw-data',
    label: '12.2 · Yaw Data',
    title: 'Lesson 12.2: Extracting Real-time Yaw Data using the AngleUnit Class',
    path: '/docs/unit-12/yaw-data',
    unitSlug: 'unit-12',
    unitLabel: 'Unit 12',
    unitTitle: 'IMU & Rotation',
  },
  {
    id: 'unit-12/field-centric',
    label: '12.3 · Field-Centric Drive',
    title: 'Lesson 12.3: Normalizing Angular Values for Field-Centric Driving',
    path: '/docs/unit-12/field-centric',
    unitSlug: 'unit-12',
    unitLabel: 'Unit 12',
    unitTitle: 'IMU & Rotation',
  },
  {
    id: 'unit-12/pitch-roll',
    label: '12.4 · Pitch & Roll',
    title: 'Lesson 12.4: Monitoring Pitch and Roll for Robot Tip Detection',
    path: '/docs/unit-12/pitch-roll',
    unitSlug: 'unit-12',
    unitLabel: 'Unit 12',
    unitTitle: 'IMU & Rotation',
  },
  {
    id: 'unit-12/imu-turn',
    label: '12.5 · IMU Turn',
    title: 'Lesson 12.5: Implementing an IMU-Corrected 90-Degree Autonomous Turn',
    path: '/docs/unit-12/imu-turn',
    unitSlug: 'unit-12',
    unitLabel: 'Unit 12',
    unitTitle: 'IMU & Rotation',
  },
  {
    id: 'unit-12/mastery-coding-challenge',
    label: 'Unit 12 · Coding Challenge',
    title: 'Unit 12 Comprehensive Coding Challenge: IMU Field-Centric Drive',
    path: '/docs/unit-12/mastery-coding-challenge',
    unitSlug: 'unit-12',
    unitLabel: 'Unit 12',
    unitTitle: 'IMU & Rotation',
  },
  {
    id: 'unit-13/encapsulation',
    label: '13.1 · Encapsulation',
    title: 'Lesson 13.1: Encapsulating Component Logic into Mechanism Classes',
    path: '/docs/unit-13/encapsulation',
    unitSlug: 'unit-13',
    unitLabel: 'Unit 13',
    unitTitle: 'OOP & Inheritance',
  },
  {
    id: 'unit-13/inheritance',
    label: '13.2 · Inheritance',
    title: 'Lesson 13.2: Extending Parent Classes for Modular Hardware Subsystems',
    path: '/docs/unit-13/inheritance',
    unitSlug: 'unit-13',
    unitLabel: 'Unit 13',
    unitTitle: 'OOP & Inheritance',
  },
  {
    id: 'unit-13/override',
    label: '13.3 · @Override',
    title: 'Lesson 13.3: Overriding Behavior with @Override for Custom Implementations',
    path: '/docs/unit-13/override',
    unitSlug: 'unit-13',
    unitLabel: 'Unit 13',
    unitTitle: 'OOP & Inheritance',
  },
  {
    id: 'unit-13/static-constants',
    label: '13.4 · Static Constants',
    title: 'Lesson 13.4: Managing Shared Constants with the static Keyword',
    path: '/docs/unit-13/static-constants',
    unitSlug: 'unit-13',
    unitLabel: 'Unit 13',
    unitTitle: 'OOP & Inheritance',
  },
  {
    id: 'unit-13/robot-class',
    label: '13.5 · Robot Class',
    title: 'Lesson 13.5: Architecting a Modular Robot Class with Nested Subsystems',
    path: '/docs/unit-13/robot-class',
    unitSlug: 'unit-13',
    unitLabel: 'Unit 13',
    unitTitle: 'OOP & Inheritance',
  },
  {
    id: 'unit-13/build-intake',
    label: '13.6 · Build Intake',
    title: 'Lesson 13.6: Build RobotConfig.java and Intake.java',
    path: '/docs/unit-13/build-intake',
    unitSlug: 'unit-13',
    unitLabel: 'Unit 13',
    unitTitle: 'OOP & Inheritance',
  },
  {
    id: 'unit-13/build-lift',
    label: '13.7 · Build Lift',
    title: 'Lesson 13.7: Build MotorMechanism.java and Lift.java',
    path: '/docs/unit-13/build-lift',
    unitSlug: 'unit-13',
    unitLabel: 'Unit 13',
    unitTitle: 'OOP & Inheritance',
  },
  {
    id: 'unit-13/build-robot-hardware',
    label: '13.8 · Build RobotHardware',
    title: 'Lesson 13.8: Build RobotHardware.java',
    path: '/docs/unit-13/build-robot-hardware',
    unitSlug: 'unit-13',
    unitLabel: 'Unit 13',
    unitTitle: 'OOP & Inheritance',
  },
  {
    id: 'unit-13/competition-teleop',
    label: '13.9 · Complete TeleOp',
    title: 'Lesson 13.9: Complete CompetitionTeleOp.java',
    path: '/docs/unit-13/competition-teleop',
    unitSlug: 'unit-13',
    unitLabel: 'Unit 13',
    unitTitle: 'OOP & Inheritance',
  },
  {
    id: 'unit-13/mastery-coding-challenge',
    label: 'Unit 13 · Coding Challenge',
    title: 'Unit 13 Comprehensive Coding Challenge: Modular Robot Architecture',
    path: '/docs/unit-13/mastery-coding-challenge',
    unitSlug: 'unit-13',
    unitLabel: 'Unit 13',
    unitTitle: 'OOP & Inheritance',
  },
  {
    id: 'unit-14/vision-portal',
    label: '14.1 · VisionPortal',
    title: 'Lesson 14.1: Configuring VisionPortal and Opening Webcam Streams',
    path: '/docs/unit-14/vision-portal',
    unitSlug: 'unit-14',
    unitLabel: 'Unit 14',
    unitTitle: 'Computer Vision',
  },
  {
    id: 'unit-14/apriltag-detection',
    label: '14.2 · AprilTag Detection',
    title: 'Lesson 14.2: Detecting Field Locations using AprilTagProcessor',
    path: '/docs/unit-14/apriltag-detection',
    unitSlug: 'unit-14',
    unitLabel: 'Unit 14',
    unitTitle: 'Computer Vision',
  },
  {
    id: 'unit-14/pose-data',
    label: '14.3 · Pose Data',
    title: 'Lesson 14.3: Extracting Detection IDs and Pose Data for Navigation',
    path: '/docs/unit-14/pose-data',
    unitSlug: 'unit-14',
    unitLabel: 'Unit 14',
    unitTitle: 'Computer Vision',
  },
  {
    id: 'unit-14/opencv-zones',
    label: '14.4 · OpenCV Zones',
    title: 'Lesson 14.4: Defining Vision Windows with OpenCV Rect Boundaries',
    path: '/docs/unit-14/opencv-zones',
    unitSlug: 'unit-14',
    unitLabel: 'Unit 14',
    unitTitle: 'Computer Vision',
  },
  {
    id: 'unit-14/multi-zone-challenge',
    label: '14.5 · Multi-Zone Vision',
    title: 'Lesson 14.5: Multi-Zone Vision Processing for Autonomous Scoring Selection',
    path: '/docs/unit-14/multi-zone-challenge',
    unitSlug: 'unit-14',
    unitLabel: 'Unit 14',
    unitTitle: 'Computer Vision',
  },
  {
    id: 'unit-14/mastery-coding-challenge',
    label: 'Unit 14 · Coding Challenge',
    title: 'Unit 14 Comprehensive Coding Challenge: Vision-Guided Autonomous',
    path: '/docs/unit-14/mastery-coding-challenge',
    unitSlug: 'unit-14',
    unitLabel: 'Unit 14',
    unitTitle: 'Computer Vision',
  },
  {
    id: 'unit-15/limelight',
    label: '15.1 · Limelight 3A',
    title: 'Lesson 15.1: Tuning Vision Pipelines on the Limelight 3A Interface',
    path: '/docs/unit-15/limelight',
    unitSlug: 'unit-15',
    unitLabel: 'Unit 15',
    unitTitle: 'Advanced Integration',
  },
  {
    id: 'unit-15/pedro-pathing',
    label: '15.2 · Pedro Pathing 3',
    title: 'Lesson 15.2: Controlling a Pedro 3 Follower',
    path: '/docs/unit-15/pedro-pathing',
    unitSlug: 'unit-15',
    unitLabel: 'Unit 15',
    unitTitle: 'Advanced Integration',
  },
  {
    id: 'unit-15/bezier-curves',
    label: '15.3 · Pedro 3 Paths',
    title: 'Lesson 15.3: Creating Pedro 3 Paths with Bézier Curves',
    path: '/docs/unit-15/bezier-curves',
    unitSlug: 'unit-15',
    unitLabel: 'Unit 15',
    unitTitle: 'Advanced Integration',
  },
  {
    id: 'unit-15/limelight-fusion',
    label: '15.4 · Limelight Fusion',
    title: 'Lesson 15.4: Global Field Localization with AprilTag and Limelight Fusion',
    path: '/docs/unit-15/limelight-fusion',
    unitSlug: 'unit-15',
    unitLabel: 'Unit 15',
    unitTitle: 'Advanced Integration',
  },
  {
    id: 'unit-15/full-autonomous',
    label: '15.5 · Pedro 3 + Ivy',
    title: 'Lesson 15.5: Coordinating a Pedro 3 Autonomous with Ivy',
    path: '/docs/unit-15/full-autonomous',
    unitSlug: 'unit-15',
    unitLabel: 'Unit 15',
    unitTitle: 'Advanced Integration',
  },
  {
    id: 'unit-15/mastery-coding-challenge',
    label: 'Unit 15 · Coding Challenge',
    title: 'Unit 15 Comprehensive Coding Challenge: Full Sensor-Fused Autonomous',
    path: '/docs/unit-15/mastery-coding-challenge',
    unitSlug: 'unit-15',
    unitLabel: 'Unit 15',
    unitTitle: 'Advanced Integration',
  },
];

export const CURRICULUM_UNIT_COUNT = CURRICULUM_UNITS.length;
// Public course metadata also counts the Unit 2-15 overview lessons.
export const CURRICULUM_LESSON_COUNT = CURRICULUM_LESSONS.length + 14;

export function getUnitBySlug(unitSlug: string): CurriculumUnit | undefined {
  return CURRICULUM_UNITS.find((unit) => unit.slug === unitSlug);
}

export function getLessonsForUnit(unitSlug: string): CurriculumLesson[] {
  return CURRICULUM_LESSONS.filter((lesson) => lesson.unitSlug === unitSlug);
}
